---

- name: "facts: Run zpool_facts"
  zpool_facts:

- name: "facts: Debug ansible_zfs_pools"
  when: fzfs_debug
  debug:
    var: ansible_zfs_pools

- name: "facts: Debug list pools"
  when: fzfs_debug
  debug:
    msg: "name [ {{ item.name }} ], size [ {{ item.size }} ], free [ {{ item.free }} ]"
  loop: "{{ ansible_zfs_pools }}"

- name: "facts: Run zfs_facts"
  zfs_facts:
    name: "{{ item.name }}"
    recurse: "{{ fzfs_facts_recurse }}"
  loop: "{{ ansible_zfs_pools }}"
  register: ansible_zfs_ds

- name: "facts: Debug ansible_zfs_ds"
  when: fzfs_debug
  debug:
    var: ansible_zfs_ds

- name: "facts: Get list of datasets"
  include_tasks: facts_include_1.yml
  loop: "{{ ansible_zfs_ds.results }}"

- name: "facts: Debug list of datasets"
  when: fzfs_debug
  debug:
    var: fzfs_datasets

# EOF
...
