---
# tasks for freebsd_zfs

- name: Include role vbotka.freebsd_postinstall task sysctl
  block:
    - name: Concatenate fp_sysctl and fzfs_sysctl
      set_fact:
        fp_sysctl: "{{ fp_sysctl|default([]) }} + {{ fzfs_sysctl }}"
    - name: Include vbotka.freebsd_postinstall sysctl
      include_role:
        name: vbotka.freebsd_postinstall
        tasks_from: sysctl.yml
  tags: fzfs_sysctl

- import_tasks: debug.yml
  when: fzfs_debug|bool
  tags: [always, fzfs_debug]

- import_tasks: rcconf.yml
  tags: fzfs_rcconf

- import_tasks: facts.yml
  tags: fzfs_facts

- import_tasks: manage.yml
  tags: fzfs_manage

# EOF
...
