---
# tasks for freebsd_zfs

- name: Include role vbotka.freebsd_postinstall task sysctl
  block:
    - name: Set kernel state fzfs_sysctl
      ansible.builtin.set_fact:
        fp_sysctl_conf: "{{ fzfs_sysctl_conf }}"
    - name: Include vbotka.freebsd_postinstall sysctl
      include_role:
        name: vbotka.freebsd_postinstall
        tasks_from: sysctl.yml
  tags: fzfs_sysctl

- name: Include role vbotka.freebsd_postinstall task loader
  block:
    - name: Configure fzfs_sysctl in /boot/loader.conf
      ansible.builtin.set_fact:
        fp_sysctl_conf: "{{ fzfs_sysctl_conf }}"
    - name: Include vbotka.freebsd_postinstall loader
      include_role:
        name: vbotka.freebsd_postinstall
        tasks_from: loader.yml
  tags: fzfs_loader

- import_tasks: debug.yml
  when: fzfs_debug|bool
  tags: [always, fzfs_debug]

- import_tasks: rcconf.yml
  tags: fzfs_rcconf

- import_tasks: facts.yml
  tags: fzfs_facts

- import_tasks: manage.yml
  tags: fzfs_manage

# EOF
...
