---

- name: "manage: Manage zfs"
  community.general.zfs:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    origin: "{{ item.origin|default(omit) }}"
    extra_zfs_properties: "{{ item.extra_zfs_properties|default(omit) }}"
  loop: "{{ fzfs_manage }}"
  loop_control:
    label: "{{ item.name }}"

- name: "manage: Set mode and ownership of zfs mountpoints"
  ansible.builtin.file:
    state: directory
    path: "{{ item.mountpoint }}"
    owner: "{{ item.owner|default(omit) }}"
    group: "{{ item.group|default(omit) }}"
    mode: "{{ item.mode|default(omit) }}"
  loop: "{{ fzfs_mountpoints }}"
  loop_control:
    label: "{{ item.mountpoint }}"
  notify: mount all zfs

# EOF
...
