---

- name: "rcconf: Configure ZFS in /etc/rc.conf"
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^\\s*{{ item.regexp }}\\s*="
    line: "{{ item.regexp }}={{ item.val }}"
    backup: "{{ fzfs_backup_conf }}"
  loop: "{{ fzfs_rcconf }}"
  notify: restart zfs

- name: "rcconf: Enable and Start zfs"
  when: fzfs_enable|bool
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^\\s*zfs_enable\\s*="
    line: "zfs_enable=\"YES\""
    backup: "{{ fzfs_backup_conf }}"
  notify: enable and start zfs

- name: "rcconf: Disable and Stop zfs"
  when: not fzfs_enable|bool
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^\\s*zfs_enable\\s*="
    line: "zfs_enable=\"NO\""
    backup: "{{ fzfs_backup_conf }}"
  notify: disable and stop zfs

- name: "rcconf: flush handlers"
  meta: flush_handlers

- name: "rcconf: Exit play if ZFS is not enabled"
  meta: end_play
  when: not fzfs_enable|bool

# EOF
...
